# Utilisez une version stable et spécifique de Node.js avec Alpine
FROM node:18.20.0-alpine

# Définir le répertoire de travail de l'application
WORKDIR /usr/src/app

# Copier les fichiers de package pour installer les dépendances
COPY frontend/package*.json ./

# Installer Angular CLI globalement et toutes les dépendances de l'application
RUN npm install -g @angular/cli@18.2.11 && npm install --legacy-peer-deps

# Copier le reste de l'application
COPY frontend/ .

# Exposer le port utilisé par Angular
EXPOSE 4200

# Utiliser npm start pour lancer ng serve
CMD ["npm", "start"]
