FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ocr/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ocr/ocr_script.py /app/ocr_script.py

CMD ["python", "ocr_script.py"]


