FROM python:3.9-slim

# Install necessary libraries
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    libgl1 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the requirements.txt file and install Python packages
COPY ocr/requirements.txt /app/requirements.txt

# Upgrade pip and install the requirements with extended timeout
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

# Copy the FastAPI script into the container
COPY ocr/ocr_script.py /app/ocr_script.py

# Expose port 5000
EXPOSE 5000

# Start the FastAPI application using Uvicorn
CMD ["uvicorn", "ocr_script:app", "--host", "0.0.0.0", "--port", "5000"]
