FROM golang:1.22.5-alpine AS builder
WORKDIR /app
COPY backend/ .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o go_api .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/go_api .
RUN chmod +x /app/go_api
EXPOSE 8080
CMD ["./go_api"]

