INSERT INTO occupants (
    id,
    created_at,
    updated_at,
    deleted_at,
    name,
    surname,
    email,
    corporation,
    phone,
    iban,
    birth_date,
    civility_id,
    domicile_address_id,
    document_receiving_method_id,
    reminder_delay,
    reminder_receiving_method_id
  )
VALUES (
    'id:bigint',
    'created_at:timestamp with time zone',
    'updated_at:timestamp with time zone',
    'deleted_at:timestamp with time zone',
    'name:text',
    'surname:text',
    'email:text',
    corporation:boolean,
    'phone:text',
    'iban:text',
    'birth_date:timestamp with time zone',
    'civility_id:bigint',
    'domicile_address_id:bigint',
    'document_receiving_method_id:bigint',
    'reminder_delay:bigint',
    'reminder_receiving_method_id:bigint'
  );