FROM python:3.9-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    libgl1 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=1000 -r requirements.txt
COPY ocr_script.py /app/ocr_script.py
EXPOSE 5000
CMD ["uvicorn", "ocr_script:app", "--host", "0.0.0.0", "--port", "5000"]
