FROM golang:1.23-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/swaggo/swag/cmd/swag@latest
COPY . .
RUN swag init
RUN go install github.com/air-verse/air@latest
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o /app/tmp/main .

FROM golang:1.23-alpine
WORKDIR /app
COPY --from=builder /app/tmp/main /app/tmp/main  
COPY --from=builder /go/bin/air /usr/local/bin/air 
COPY --from=builder /app/docs /app/docs
RUN chmod +x /app/tmp/main  
EXPOSE 8080
CMD ["air"]

