FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/air-verse/air@latest
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o /app/tmp/main .

FROM golang:1.23-alpine
WORKDIR /app
COPY --from=builder /app/tmp/main /app/tmp/main  
COPY --from=builder /go/bin/air /usr/local/bin/air 
RUN chmod +x /app/tmp/main  
EXPOSE 8080
CMD ["air"]

