remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
repository: Sebiche09/gestion-syndic
title: Documentation du projet SOGIM-syndic
description: Ce site est la documentation du projet SOGIM-syndic